### ISSUE TITLE
prod django's dockerfile

### ISSUE THREAD

**Issue by kheiripour** [AliBigdeli/Ultimate-Django3.2-Template#1]
Hi Ali,
Its a great and useful template that you kindly provided and explained in your video.
There are somethings I should search and study more to know, but one thing I want to ask is:
At line 24 , docker-compose-prod.yml , you declared stage docker file for your backend container. If that is true, can you explain why?
With thanks and appreciation.

**Comment by AliBigdeli** [comment]
Thanks for addressing the issue, well i was testing the two stage dockerfile in my template and upgrading it so i did a mistake and didnt revert it. 
So simply its a mistake i did. 😁🙏 and btw stage and production now can be used as one in the mean time till i fix the dependecy issues with some modules.
